image:
  file: .gitpod.Dockerfile
tasks:
  - init: pip3 install -r requirements.txt
    command: mkdocs serve --dev-addr localhost:3000 -v --livereload
ports:
  - port: 8080
    onOpen: notify
  - port: 8000
    onOpen: notify
  - port: 3000
    onOpen: notify