resource_rules:
  issues:
    rules:
      - name: Triaging new issues
        conditions:
          date:
            attribute: created_at
            condition: newer_than
            interval_type: minutes
            interval: 1
          state: opened
          labels:
            - No Label
        actions:
          labels:
            - documentation
          comment:
  merge_requests:
    rules:
      []
