resource_rules:
  issues:
    rules:
      - name: Triaging new issues
        conditions:
          date:
            attribute: created_at
            condition: newer_than
            interval_type: hours
            interval: 6
          state: opened
          labels:
            - No Label
        actions:
          labels:
            - documentation
            - feedback
          comment: |
            Hi,

            Thank you for creating an new issue. One of our team members will contact you soon
            and we can't promise that we can reply you shortly.

            In an meanwhile, we are advised to [read the documentation] and [search for solved issues]
            in our Issue Tracker.

            Regards,
            Your Friends at The Pins Team
            ---

            [read the documentation]: https://en.handbooksbythepins.cf
            [search for solved issues]:
  merge_requests:
    rules:
      - name: Triaging new merge requests
        conditions:
          date:
            attribute: created_at
            condition: newer_than
            interval_type: hours
            interval_type: 6
        actions:
          labels:
            - "work in progress"
